### PR TITLE
Rb group tech

### PR DESCRIPTION
**Pull request by rsbabcock**
# Description

I've added a component folder called groupTech. This includes the group image and the combined list of tech skills in image format.

The images are listed as state in the groupTech.js folder.

For whoever is doing the party button, the group image will need to be swapped out for a funny version with state. See Riley for more info.

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

## Testing:

1.
```
git fetch --all
git checkout rb-groupTech
npm start
```
Make sure placeholder images are there 
Please look at the tech stack and make it looks good

### CODE REVIEW

**Comment by obscure-shadow** [comment]
looks good to me :shipit: you could add digital ocean to the tech stack some of us are doing that with steve, also maybe vscode icon and npm...  but that's more like website planning stuff, not my deal. as far as testing goes, it all looks good :)

**Comment by MrErin** [comment]
Testing-wise, it gets my 👍 . Merge it.

Plus one to David's comment.

Additionally, I think we should consider using the Devicons (https://konpa.github.io/devicon/) that have the name of the tech integrated into the image. This is based on some feedback from Kristin on resumes. She said often the person reviewing the resume (or in this case, the website,) isn't a tech person and might not recognize the techs indicated by the images. I'm not married to the idea since it can clutter up the images, but it's yet another thing to consider. 🤷‍♀️

**Comment by rsbabcock** [comment]
@MrErin  =  I Like, I'll do it

**Comment by rsbabcock** [comment]
@MrErin Changed out images, does take up more room, but yeah, they're there

**Comment by obscure-shadow** [comment]
still working for me, they do look a little smashed up though... at this point i would not worry too much about it, probably best to get the rest of the functionality down then address the finer points later... unless you are waiting on other stuff... then by all means go crazy

**Pull request merged**
