### PR TITLE
Rb student profile

### PR DESCRIPTION
**Pull request by rsbabcock**
# Description

I added search functionality to navbar as well as a profile page which includes all student data, including both serious and funny pictures. 

The search functionality is only for first name and last name or either one.

Stretch goal would have a page comes up which shows search results options that come up based on search terms that are individual.

This would need to be done by refactoring the existing search parameters to utlize individual letters as they're typed.

## Testing
```
git fetch --all
git checkout rb-studentProfile
npm start 
```
(start only if not running server already)

To test, search for several names in search bar, first name or last name or both
Once in a profile view click on the brand logo to go back to the main view
A possible addition would be to add the viewHandler to the title of cohort 25 as well.
Test the modals to make sure they're still working as well as any other functionality to make sure nothing is broken.

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by RileyMathews** [comment]
I can't seem to get the search to actually fire. It seems from the code that the 'enter' key should fire the search but its not working for me.

**Comment by MrErin** [comment]
I was able to search fine, using the following parameters:
 * first name only, lowercase & uppercase
 * last name only, lowercase & uppercase
 * full name, lowercase & uppercase

The only time I had trouble with the search was when searching for just the first name of "erin" because there are two of us.

Also double checked the profile modals. They're still working.

👍

**Comment by MrErin** [comment]
One more note though: My last name is "Meaker", not "Meeker". The filenames of my photos are spelled incorrectly. Not worth stopping the presses over, but I'd like it changed before publication 😆

**Comment by rsbabcock** [comment]
On it
*Rachael S. Babcock*

**Comment by rsbabcock** [comment]
@MrErin  I misspelled your last name when I renamed the images, not the photography, that should be corrected now. It was spelled correctly on the actual name though. Let me know if I've missed anything else.

@RileyMathews  Can we sit down on monday to go over code on the search functionality?

**Comment by rsbabcock** [comment]
🚢 and we'll change the picture out after

**Pull request closed without merging**
